spring:
  profiles:
    default: local

  datasource:
    url: jdbc:h2:mem:~/sd
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none

---
spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
      path: /h2-console
---
spring:
  config:
    activate:
      on-profile: test

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    defer-datasource-initialization: false

  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: never